repos:
  - repo: local
    hooks:
      - id: rustfmt
        name: rustfmt
        description: Check if all files follow the rustfmt style
        entry: cargo fmt --all -- --check --color always
        language: rust
        types: [ rust ]
        pass_filenames: false

      - id: check
        name: check
        description: Standard check
        entry: cargo check
        language: system
        types: [ rust ]
        pass_filenames: false

      - id: clippy
        name: clippy
        description: More rigorous check
        entry: cargo clippy -- -D warnings
        language: rust
        pass_filenames: false

      - id: test
        name: test
        description: Run tests
        entry: cargo test
        language: rust
        types: [ rust ]
        pass_filenames: false
